
image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli
  - npm install

build:
  stage: build
  script:
    - ng build --configuration production --base-href /$CI_PROJECT_NAME/
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - mv dist/public dist/$CI_PROJECT_NAME
    - mv dist $CI_PROJECT_NAME
  artifacts:
    paths:
      - $CI_PROJECT_NAME
  only:
    - main
  environment:
    name: production
    url: "https://pedamalluv.gitlab.io/guess-word/"
